version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx.docker
    container_name: dm-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - ./conf/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - web

  db:
    image: mysql:5.7
    container_name: dm-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dm-django
      MYSQL_ROOT_PASSWORD: hogehoge
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./conf/db:/etc/mysql/conf.d

  web:
    build: 
      context: ./
      dockerfile: ./docker/web.docker
    container_name: dm-web
    command: uwsgi --socket :8001 --module dm-site.wsgi
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db
      - redis

  redis:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/redis.docker
    container_name: dm-redis
    volumes:
       - ./redis:/data
    ports:
       - "6379:6379"
    command: redis-server --appendonly yes
